### ISSUE TITLE
2023.5 update causes strange effect

### ISSUE THREAD

**Issue by Remko76** [r-renato/ha-card-weather-conditions#102]
I upgraded Homeassistant to the latest 2023.5 version and now see a strange overlay effect with this card in the companion app as well as in a mobile chrome browser.

It seems the card does not respect layers of the UI or so. It does not hide behind the top bar on scrolling and also the side menu does not lie on top of this card. I hope the screenshot clarifies it..

![image](https://user-images.githubusercontent.com/75678314/236131123-d64bc23e-010c-4700-9f3d-70102e73cde8.png)

**Comment by darkstoneathome** [comment]
Same here. Occurs in the Android App and also in the web browser.

**Comment by bram2202** [comment]
Same here.
I'm on 2023.5.2, but also noticed this behavior on 2023.4 .x

![image](https://github.com/r-renato/ha-card-weather-conditions/assets/6704538/d8946f22-ed0c-45c2-a64a-59fda7004d83)

**Comment by Remko76** [comment]
@bram2202 : how did you guys it locally? I tried to modify the local .js file in "/config/www/community/ha-card-weather-conditions/ha-card-weather-conditions.js”

removed the 6 z-index entries, saved, rebooted, cleared cache etc. but no effect.

**Comment by Remko76** [comment]
I actually uninstalled it completely, added your branch @bram2202  as custom repo in hacs, but still have the same issue...

**Comment by bram2202** [comment]
@Remko76 sorry for the slow response.

I missed some `z-index: 200` in my pull request, I updated it.

If you modify your local file in the `www\community\ha-card-weather-conditions` folder, 
dont forget to update your resources in HA:
1. Go to `<your-instance>/config/lovelace/resources`  
2. Find the `ha-card-weather-conditions` resource and edit it.
3. change the `hacstag` number to someting else and save.
4. hard refresh your browser.

The change in number tells your browser that the file is new and needs to be loaded instead of getting it from cache.

It fixed it on my dashboard:

![image](https://github.com/r-renato/ha-card-weather-conditions/assets/6704538/feb06c21-17cf-4d91-aaf4-c1d379e58eb5)

**Comment by Remko76** [comment]
Cool, thanks for the reply. That did the trick!!

**Comment by gfay63** [comment]
@bram2202 , LOVE this extension! However, I have this same "transparent" issue and it's driving me batty. 

I could not find "hacstag" in the ha-card-weather-conditions.js file. I also tried re-downloading the latest version and no luck.

How can I fix this?

Here's an example trying to edit something and it happens to be behind.

![image](https://github.com/r-renato/ha-card-weather-conditions/assets/4573115/d8138ff9-385c-4077-bb51-484366a7c1dc)

**Comment by bram2202** [comment]
@gfay63 you can try to add my fork as an extra repository in hacs, disable this plugin and install the one from my fork.

**Comment by gfay63** [comment]
@bram2202 Well that worked! Not sure why, but it did!  Thank you! :) 

Only thing I'm worried about is missing updates to the original.

**Comment by bram2202** [comment]
Keep your eyes one this PR: https://github.com/r-renato/ha-card-weather-conditions/pull/103.
If its merged you can remove my fork and go back to the original.

**Comment by zollek** [comment]
Thanks for the solution. I've modified the oryginal .js and .js.gz files.
I've my own Polish translation with modified icons to fit AccuWeather.
